title: Data Lab Training
training_title: 2023 May Single-cell RNA-Seq Workshop
# The name of the repository (e.g., 2020-may-training)
# We use training-specific-template to help with development
repository: 2023-may-training
# Full URL to the repository
# Again, using training-specific-template to aid in development
repository_url: https://github.com/AlexsLemonade/2023-may-training
start_date: 2023-05-15
end_date: 2023-05-19
# Specific release in AlexsLemonade/training-modules
# We use master to make development easier
release_tag: 2023-may
# The Docker user will almost always be ccdl, which is why this is here
docker_user: ccdl
docker_repo: training_rnaseq
docker_tag: 2023-may

# Theme and theme options
theme: minima
# Pages to appear in site header.
header_home:
  workshop/HOME.md
header_pages:
  # Note that when first cloned, the `workshop` directory will not exist,
  # as described at https://github.com/AlexsLemonade/training-specific-template#customizing-the-new-repository-for-an-individual-training-workshop
  - workshop/SCHEDULE.md
  - workshop/workshop-structure.md
  - workshop/workshop-materials.md
  - workshop/resources-for-consultation-sessions.md
  - working-with-your-data/working-with-your-own-data.md
  - workshop/posting-errors-guidelines.md
author: Childhood Cancer Data Lab
email: training@ccdatalab.org
twitter_username: CancerDataLab
github_username:  AlexsLemonade
